# Generated by Django 4.2.20 on 2025-04-18 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(null=True)),
                ("name", models.CharField(default="", max_length=150)),
                ("sku", models.CharField(max_length=30, unique=True)),
                ("description", models.CharField(default="", max_length=1024)),
                ("weight_onces", models.PositiveIntegerField(default=0)),
                ("is_active", models.SmallIntegerField(default=1)),
            ],
            options={
                "ordering": ("name", "-created_at"),
            },
        ),
    ]
