# Generated by Django 4.2.20 on 2025-04-18 20:11

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('core', '0001_initial')
    ]

    operations = [
        migrations.RunSQL(
            sql=[("INSERT INTO core_part (name, created_at, sku, description, weight_onces, is_active) VALUES (%s,%s,%s,%s,%s,%s);", ['Heavy coil', timezone.now(), 'SDJDDH8223DHJ', 'Tightly wound nickel-gravy alloy spring', 22, 1])],
            reverse_sql=[("DELETE FROM core_parts WHERE sku = %s", ['SDJDDH8223DHJ'])]
        ),
        migrations.RunSQL(
            sql=[("INSERT INTO core_part (name, created_at, sku, description, weight_onces, is_active) VALUES (%s,%s,%s,%s,%s,%s);", ['Reverse lever', timezone.now(), 'DCMM39823DSJD', 'Attached to provide inverse leverage', 9, 0])],
            reverse_sql=[("DELETE FROM core_parts WHERE sku = %s", ['DCMM39823DSJD'])]
        ),
        migrations.RunSQL(
            sql=[("INSERT INTO core_part (name, created_at, sku, description, weight_onces, is_active) VALUES (%s,%s,%s,%s,%s,%s);", ['Macrochip', timezone.now(), 'OWDD823011DJSD', 'Used for heavy-load computing', 2, 1])],
            reverse_sql=[("DELETE FROM core_parts WHERE sku = %s", ['OWDD823011DJSD'])]
        ),                
    ]
