# Generated by Django 4.2.20 on 2025-04-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_insert_parts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="part",
            old_name="weight_onces",
            new_name="weight_ounces",
        ),
    ]
